name: Validation-code-python

on:
  push:
    branches: [master]
    paths:
      - '*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.10.4
          architecture: x64
      - name: install Flake8
        run: pip install flake8
      - name: run Flake8
        uses: suo/flake8-github-action@v1
        with:
          checkName: 'build'